import { GroundStation as ApiGroundStation } from "../types";

// Extended interface for display purposes (combines different ground station sources)
export interface DisplayGroundStation {
  id: string;
  name: string;
  source: "api" | "predefined" | "custom";
  country: string;
  city?: string;
  latitude: number;
  longitude: number;
  altitude: number; // meters above sea level
  status: "Active" | "Inactive" | "Maintenance" | "Decommissioned";
  frequency?: string; // MHz
  bandType?: "S" | "X" | "Ka" | "Ku" | "L" | "C" | "Unknown";
  elevation?: number; // minimum elevation angle
  azimuth?: number; // antenna azimuth range
  operator?: string;
  established?: string; // establishment date
  description?: string;
  lastUpdate: string;
}

// Predefined major ground stations around the world
const PREDEFINED_GROUND_STATIONS: DisplayGroundStation[] = [
  {
    id: "predefined-1",
    name: "Goldstone Deep Space Communications Complex",
    source: "predefined",
    country: "USA",
    city: "Goldstone, California",
    latitude: 35.4267,
    longitude: -116.8900,
    altitude: 1036,
    status: "Active",
    frequency: "2290-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "NASA/JPL",
    established: "1958-10-01",
    description: "NASA Deep Space Network station",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-2", 
    name: "Madrid Deep Space Communications Complex",
    source: "predefined",
    country: "Spain",
    city: "Robledo de Chavela",
    latitude: 40.4552,
    longitude: -4.2517,
    altitude: 834,
    status: "Active",
    frequency: "2270-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "NASA/ESA",
    established: "1965-05-17",
    description: "NASA Deep Space Network station in Europe",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-3",
    name: "Canberra Deep Space Communications Complex", 
    source: "predefined",
    country: "Australia",
    city: "Tidbinbilla",
    latitude: -35.4014,
    longitude: 148.9819,
    altitude: 692,
    status: "Active",
    frequency: "2290-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "NASA/CSIRO",
    established: "1965-03-19",
    description: "NASA Deep Space Network station in Australia",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-4",
    name: "ESOC - European Space Operations Centre",
    source: "predefined",
    country: "Germany",
    city: "Darmstadt",
    latitude: 49.8728,
    longitude: 8.6512,
    altitude: 144,
    status: "Active",
    frequency: "2025-2110",
    bandType: "S",
    elevation: 10,
    azimuth: 360,
    operator: "ESA",
    established: "1967-09-08",
    description: "European Space Agency mission control center",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-5",
    name: "Wallops Flight Facility",
    source: "predefined",
    country: "USA",
    city: "Wallops Island, Virginia",
    latitude: 37.9407,
    longitude: -75.4663,
    altitude: 12,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "NASA",
    established: "1945-07-04",
    description: "NASA rocket range and spaceport",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-6",
    name: "Johnson Space Center",
    source: "predefined",
    country: "USA",
    city: "Houston, Texas",
    latitude: 29.5586,
    longitude: -95.0890,
    altitude: 16,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "NASA",
    established: "1961-09-19",
    description: "NASA mission control center for human spaceflight",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-7",
    name: "Kourou Space Centre",
    source: "predefined",
    country: "France",
    city: "Kourou, French Guiana",
    latitude: 5.2389,
    longitude: -52.7683,
    altitude: 17,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "ESA/CNES",
    established: "1964-04-14",
    description: "European spaceport",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-8",
    name: "Baikonur Cosmodrome",
    source: "predefined",
    country: "Kazakhstan",
    city: "Baikonur",
    latitude: 45.965,
    longitude: 63.305,
    altitude: 90,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "Roscosmos",
    established: "1955-06-02",
    description: "World's first and largest operational space launch facility",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-9",
    name: "Tanegashima Space Center",
    source: "predefined",
    country: "Japan",
    city: "Tanegashima",
    latitude: 30.4008,
    longitude: 130.9681,
    altitude: 194,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "JAXA",
    established: "1969-10-01",
    description: "Japan's primary large rocket launch site",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-10",
    name: "Jiuquan Satellite Launch Center",
    source: "predefined",
    country: "China",
    city: "Jiuquan",
    latitude: 40.958,
    longitude: 100.291,
    altitude: 1000,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "CNSA",
    established: "1958-10-20",
    description: "China's first rocket launch site",
    lastUpdate: new Date().toISOString(),
  },
  // European Space Agency Stations
  {
    id: "predefined-11",
    name: "New Norcia Station",
    source: "predefined",
    country: "Australia",
    city: "New Norcia, Western Australia",
    latitude: -31.048,
    longitude: 116.191,
    altitude: 252,
    status: "Active",
    frequency: "2110-2120",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "ESA",
    established: "2003-04-01",
    description: "ESA's first deep space ground station",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-12",
    name: "Cebreros Station",
    source: "predefined",
    country: "Spain",
    city: "Cebreros",
    latitude: 40.453,
    longitude: -4.368,
    altitude: 794,
    status: "Active",
    frequency: "2110-2120",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "ESA",
    established: "2005-09-28",
    description: "ESA deep space tracking station",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-13",
    name: "Malargüe Station",
    source: "predefined",
    country: "Argentina",
    city: "Malargüe",
    latitude: -35.776,
    longitude: -69.398,
    altitude: 1550,
    status: "Active",
    frequency: "2110-2120",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "ESA",
    established: "2012-12-01",
    description: "ESA's third deep space ground station",
    lastUpdate: new Date().toISOString(),
  },
  // Additional NASA Stations
  {
    id: "predefined-14",
    name: "White Sands Complex",
    source: "predefined",
    country: "USA",
    city: "Las Cruces, New Mexico",
    latitude: 32.3382,
    longitude: -106.6113,
    altitude: 1237,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "NASA",
    established: "1959-01-01",
    description: "NASA satellite tracking and data relay",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-15",
    name: "Poker Flat Research Range",
    source: "predefined",
    country: "USA",
    city: "Fairbanks, Alaska",
    latitude: 65.1294,
    longitude: -147.4719,
    altitude: 213,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "NASA",
    established: "1968-01-01",
    description: "NASA sounding rocket range",
    lastUpdate: new Date().toISOString(),
  },
  // International Stations
  {
    id: "predefined-16",
    name: "Svalbard Satellite Station",
    source: "predefined",
    country: "Norway",
    city: "Longyearbyen, Svalbard",
    latitude: 78.229,
    longitude: 15.407,
    altitude: 458,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "Kongsberg Satellite Services",
    established: "1997-01-01",
    description: "Arctic satellite ground station",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-17",
    name: "Redu Station",
    source: "predefined",
    country: "Belgium",
    city: "Redu",
    latitude: 50.002,
    longitude: 5.146,
    altitude: 407,
    status: "Active",
    frequency: "2110-2120",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "ESA",
    established: "1968-01-01",
    description: "ESA satellite control center",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-18",
    name: "Villafranca Satellite Tracking Station",
    source: "predefined",
    country: "Spain",
    city: "Villafranca del Castillo",
    latitude: 40.446,
    longitude: -3.952,
    altitude: 665,
    status: "Active",
    frequency: "2110-2120",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "ESA",
    established: "1974-01-01",
    description: "ESA satellite operations center",
    lastUpdate: new Date().toISOString(),
  },
  // Russian Stations
  {
    id: "predefined-19",
    name: "Plesetsk Cosmodrome",
    source: "predefined",
    country: "Russia",
    city: "Plesetsk",
    latitude: 62.957,
    longitude: 40.577,
    altitude: 173,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "Roscosmos",
    established: "1957-01-11",
    description: "Russian spaceport and tracking station",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-20",
    name: "Baikonur Cosmodrome",
    source: "predefined",
    country: "Kazakhstan",
    city: "Baikonur",
    latitude: 45.965,
    longitude: 63.305,
    altitude: 90,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "Roscosmos",
    established: "1955-06-02",
    description: "World's first and largest operational spaceport",
    lastUpdate: new Date().toISOString(),
  },
  // Commercial and Research Stations
  {
    id: "predefined-21",
    name: "Inmarsat Goonhilly",
    source: "predefined",
    country: "United Kingdom",
    city: "Cornwall",
    latitude: 50.048,
    longitude: -5.180,
    altitude: 88,
    status: "Active",
    frequency: "1626-1660",
    bandType: "L",
    elevation: 5,
    azimuth: 360,
    operator: "Goonhilly Earth Station",
    established: "1962-07-11",
    description: "Commercial satellite communications",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-22",
    name: "Fucino Space Centre",
    source: "predefined",
    country: "Italy",
    city: "Fucino",
    latitude: 42.0,
    longitude: 13.6,
    altitude: 669,
    status: "Active",
    frequency: "2110-2120",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "Telespazio",
    established: "1963-01-01",
    description: "European satellite control center",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-23",
    name: "Kiruna Station",
    source: "predefined",
    country: "Sweden",
    city: "Kiruna",
    latitude: 67.857,
    longitude: 21.060,
    altitude: 390,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "SSC (Swedish Space Corporation)",
    established: "1967-01-01",
    description: "Polar orbiting satellite ground station",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-24",
    name: "Alice Springs",
    source: "predefined",
    country: "Australia",
    city: "Alice Springs",
    latitude: -23.7951,
    longitude: 133.8890,
    altitude: 547,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "Department of Defence Australia",
    established: "1969-01-01",
    description: "Joint defense facility satellite tracking",
    lastUpdate: new Date().toISOString(),
  },
  // Asian Stations
  {
    id: "predefined-25",
    name: "Kumsan Satellite Control Center",
    source: "predefined",
    country: "South Korea",
    city: "Kumsan",
    latitude: 36.463,
    longitude: 127.495,
    altitude: 200,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "KARI",
    established: "1990-01-01",
    description: "Korean satellite control facility",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-26",
    name: "Hassan Station",
    source: "predefined",
    country: "India",
    city: "Hassan, Karnataka",
    latitude: 13.1067,
    longitude: 76.6309,
    altitude: 827,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "ISRO",
    established: "1975-01-01",
    description: "ISRO satellite tracking and ranging station",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-27",
    name: "Dongara Station",
    source: "predefined",
    country: "Australia",
    city: "Dongara, Western Australia",
    latitude: -29.2458,
    longitude: 114.9347,
    altitude: 34,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "Optus",
    established: "1985-01-01",
    description: "Commercial satellite tracking station",
    lastUpdate: new Date().toISOString(),
  },
  // South American Stations
  {
    id: "predefined-28",
    name: "Kourou Space Centre",
    source: "predefined",
    country: "France",
    city: "Kourou, French Guiana",
    latitude: 5.239,
    longitude: -52.768,
    altitude: 16,
    status: "Active",
    frequency: "2110-2120",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "ESA/CNES",
    established: "1964-04-14",
    description: "European spaceport",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-29",
    name: "Bamberton Station",
    source: "predefined",
    country: "Canada",
    city: "British Columbia",
    latitude: 48.583,
    longitude: -123.533,
    altitude: 158,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "CSA",
    established: "1972-01-01",
    description: "Canadian satellite tracking facility",
    lastUpdate: new Date().toISOString(),
  },
  // African and Middle Eastern Stations
  {
    id: "predefined-30",
    name: "Hartebeesthoek Radio Astronomy Observatory",
    source: "predefined",
    country: "South Africa",
    city: "Krugersdorp",
    latitude: -25.890,
    longitude: 27.685,
    altitude: 1416,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "SANSA",
    established: "1961-01-01",
    description: "South African satellite tracking station",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-31",
    name: "McMurdo Station",
    source: "predefined",
    country: "Antarctica",
    city: "Ross Island",
    latitude: -77.8419,
    longitude: 166.6863,
    altitude: 50,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "US Antarctic Program",
    established: "1955-12-01",
    description: "Antarctic research station communications",
    lastUpdate: new Date().toISOString(),
  },
  // Additional Commercial and Research Stations
  {
    id: "predefined-32",
    name: "Perth Station",
    source: "predefined",
    country: "Australia",
    city: "Perth, Western Australia",
    latitude: -31.8023,
    longitude: 115.8718,
    altitude: 20,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "Lockheed Martin",
    established: "1987-01-01",
    description: "Commercial satellite operations",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-33",
    name: "Santiago Station",
    source: "predefined",
    country: "Chile",
    city: "Santiago",
    latitude: -33.1506,
    longitude: -70.6840,
    altitude: 570,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "ESA",
    established: "1980-01-01",
    description: "South American tracking station",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-34",
    name: "Singapore Station",
    source: "predefined",
    country: "Singapore",
    city: "Singapore",
    latitude: 1.3521,
    longitude: 103.8198,
    altitude: 15,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "SingTel Satellite",
    established: "1998-01-01",
    description: "Southeast Asian satellite hub",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-35",
    name: "Dongfang Station",
    source: "predefined",
    country: "China",
    city: "Hainan",
    latitude: 19.27,
    longitude: 108.62,
    altitude: 108,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "CNSA",
    established: "2004-01-01",
    description: "Chinese satellite tracking station",
    lastUpdate: new Date().toISOString(),
  },
  // Critical Missing Stations - World's Most Important
  {
    id: "predefined-36",
    name: "Kennedy Space Center",
    source: "predefined",
    country: "USA",
    city: "Cape Canaveral, Florida",
    latitude: 28.5721,
    longitude: -80.6480,
    altitude: 3,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "NASA",
    established: "1962-07-01",
    description: "NASA's primary launch center for human spaceflight",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-37",
    name: "Vandenberg Space Force Base",
    source: "predefined",
    country: "USA",
    city: "Lompoc, California",
    latitude: 34.7420,
    longitude: -120.5724,
    altitude: 112,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "US Space Force",
    established: "1958-10-04",
    description: "Primary West Coast launch site for polar and sun-synchronous orbits",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-38",
    name: "Cheyenne Mountain Complex",
    source: "predefined",
    country: "USA",
    city: "Colorado Springs, Colorado",
    latitude: 38.7434,
    longitude: -104.8465,
    altitude: 1951,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "US Space Command",
    established: "1966-02-06",
    description: "NORAD/US Space Command tracking center",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-39",
    name: "Schriever Space Force Base",
    source: "predefined",
    country: "USA",
    city: "Colorado Springs, Colorado",
    latitude: 38.8044,
    longitude: -104.5269,
    altitude: 1897,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "US Space Force",
    established: "1983-01-01",
    description: "GPS Master Control Station",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-40",
    name: "Gagarin's Start (Site 1/5)",
    source: "predefined",
    country: "Kazakhstan",
    city: "Baikonur Cosmodrome",
    latitude: 45.920,
    longitude: 63.342,
    altitude: 90,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "Roscosmos",
    established: "1957-05-15",
    description: "Historic launch pad - first human spaceflight",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-41",
    name: "Xichang Satellite Launch Center",
    source: "predefined",
    country: "China",
    city: "Xichang, Sichuan",
    latitude: 28.2467,
    longitude: 102.0264,
    altitude: 1825,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "CNSA",
    established: "1984-01-01",
    description: "China's primary geostationary satellite launch site",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-42",
    name: "Taiyuan Satellite Launch Center",
    source: "predefined",
    country: "China",
    city: "Taiyuan, Shanxi",
    latitude: 39.1423,
    longitude: 111.9671,
    altitude: 1500,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "CNSA",
    established: "1968-01-01",
    description: "China's primary sun-synchronous orbit launch site",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-43",
    name: "Wenchang Space Launch Site",
    source: "predefined",
    country: "China",
    city: "Wenchang, Hainan",
    latitude: 19.6143,
    longitude: 110.9511,
    altitude: 46,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "CNSA",
    established: "2016-06-25",
    description: "China's newest and most advanced launch site",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-44",
    name: "Satish Dhawan Space Centre",
    source: "predefined",
    country: "India",
    city: "Sriharikota, Andhra Pradesh",
    latitude: 13.7199,
    longitude: 80.2304,
    altitude: 3,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "ISRO",
    established: "1971-10-09",
    description: "India's primary rocket launch center",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-45",
    name: "Uchinoura Space Center",
    source: "predefined",
    country: "Japan",
    city: "Kimotsuki, Kagoshima",
    latitude: 31.2516,
    longitude: 131.0789,
    altitude: 195,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "JAXA",
    established: "1962-02-01",
    description: "Japan's solid rocket launch center",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-46",
    name: "Vostochny Cosmodrome",
    source: "predefined",
    country: "Russia",
    city: "Amur Oblast",
    latitude: 51.8844,
    longitude: 128.3344,
    altitude: 291,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "Roscosmos",
    established: "2016-04-28",
    description: "Russia's newest spaceport in Far East",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-47",
    name: "Guiana Space Centre",
    source: "predefined",
    country: "France",
    city: "Kourou, French Guiana",
    latitude: 5.236,
    longitude: -52.768,
    altitude: 17,
    status: "Active",
    frequency: "2110-2120",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "ESA/CNES/Arianespace",
    established: "1964-04-14",
    description: "Europe's spaceport - Ariane launch complex",
    lastUpdate: new Date().toISOString(),
  },
  // Critical Deep Space and Research Stations
  {
    id: "predefined-48",
    name: "Arecibo Observatory",
    source: "predefined",
    country: "Puerto Rico",
    city: "Arecibo",
    latitude: 18.3464,
    longitude: -66.7528,
    altitude: 497,
    status: "Decommissioned",
    frequency: "1400-1427",
    bandType: "L",
    elevation: 5,
    azimuth: 360,
    operator: "NSF",
    established: "1963-11-01",
    description: "Former world's largest single-aperture radio telescope",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-49",
    name: "Parkes Observatory",
    source: "predefined",
    country: "Australia",
    city: "Parkes, New South Wales",
    latitude: -32.9980,
    longitude: 148.2635,
    altitude: 392,
    status: "Active",
    frequency: "1400-1427",
    bandType: "L",
    elevation: 5,
    azimuth: 360,
    operator: "CSIRO",
    established: "1961-10-31",
    description: "Famous radio telescope - Apollo 11 moon landing coverage",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-50",
    name: "Green Bank Observatory",
    source: "predefined",
    country: "USA",
    city: "Green Bank, West Virginia",
    latitude: 38.4331,
    longitude: -79.8397,
    altitude: 824,
    status: "Active",
    frequency: "1400-1427",
    bandType: "L",
    elevation: 5,
    azimuth: 360,
    operator: "Green Bank Observatory",
    established: "1958-01-01",
    description: "World's largest fully steerable radio telescope",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-51",
    name: "Jodrell Bank Observatory",
    source: "predefined",
    country: "United Kingdom",
    city: "Cheshire",
    latitude: 53.2367,
    longitude: -2.3071,
    altitude: 89,
    status: "Active",
    frequency: "1400-1427",
    bandType: "L",
    elevation: 5,
    azimuth: 360,
    operator: "University of Manchester",
    established: "1945-12-14",
    description: "Historic radio astronomy observatory - Lovell Telescope",
    lastUpdate: new Date().toISOString(),
  },
  // Strategic Communication Stations
  {
    id: "predefined-52",
    name: "Pine Gap",
    source: "predefined",
    country: "Australia",
    city: "Alice Springs, Northern Territory",
    latitude: -23.7987,
    longitude: 133.7378,
    altitude: 547,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "CIA/ASD",
    established: "1970-12-09",
    description: "Joint US-Australian satellite intelligence facility",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-53",
    name: "Buckley Space Force Base",
    source: "predefined",
    country: "USA",
    city: "Aurora, Colorado",
    latitude: 39.7016,
    longitude: -104.7518,
    altitude: 1724,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "US Space Force",
    established: "1942-01-01",
    description: "Space surveillance and missile warning",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-54",
    name: "Thule Air Base",
    source: "predefined",
    country: "Greenland",
    city: "Qaanaaq",
    latitude: 76.5319,
    longitude: -68.7032,
    altitude: 251,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "US Space Force",
    established: "1943-01-01",
    description: "Northernmost space surveillance radar",
    lastUpdate: new Date().toISOString(),
  },
  // Commercial Space Stations
  {
    id: "predefined-55",
    name: "Boca Chica Starship Facility",
    source: "predefined",
    country: "USA",
    city: "Brownsville, Texas",
    latitude: 25.997,
    longitude: -97.157,
    altitude: 12,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "SpaceX",
    established: "2019-01-01",
    description: "SpaceX Starship development and launch facility",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-56",
    name: "Rocket Lab Launch Complex",
    source: "predefined",
    country: "New Zealand",
    city: "Mahia Peninsula",
    latitude: -39.2608,
    longitude: 177.8640,
    altitude: 145,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "Rocket Lab",
    established: "2017-05-25",
    description: "Commercial small satellite launch facility",
    lastUpdate: new Date().toISOString(),
  },
  // Additional Critical International Stations
  {
    id: "predefined-57",
    name: "Semnan Space Center",
    source: "predefined",
    country: "Iran",
    city: "Semnan",
    latitude: 35.2344,
    longitude: 53.9209,
    altitude: 1131,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "ISA",
    established: "2009-02-02",
    description: "Iran's primary satellite launch center",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-58",
    name: "Palmachim Airbase",
    source: "predefined",
    country: "Israel",
    city: "Palmachim",
    latitude: 31.8979,
    longitude: 34.6910,
    altitude: 54,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "IAF",
    established: "1971-01-01",
    description: "Israel's primary satellite launch site",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-59",
    name: "Naro Space Center",
    source: "predefined",
    country: "South Korea",
    city: "Goheung, South Jeolla",
    latitude: 34.4312,
    longitude: 127.5351,
    altitude: 50,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "KARI",
    established: "2009-08-25",
    description: "South Korea's primary rocket launch center",
    lastUpdate: new Date().toISOString(),
  },
  {
    id: "predefined-60",
    name: "Alcantara Launch Center",
    source: "predefined",
    country: "Brazil",
    city: "Alcântara, Maranhão",
    latitude: -2.3117,
    longitude: -44.3964,
    altitude: 46,
    status: "Active",
    frequency: "2200-2300",
    bandType: "S",
    elevation: 5,
    azimuth: 360,
    operator: "AEB",
    established: "1990-01-01",
    description: "Brazil's equatorial rocket launch site",
    lastUpdate: new Date().toISOString(),
  }
];

// Convert API ground station to display format
export const convertApiGroundStationToDisplay = (gs: ApiGroundStation): DisplayGroundStation => ({
  id: `api-${gs._id}`,
  name: gs.name,
  source: "api",
  country: gs.country || "Unknown",
  city: gs.city,
  latitude: gs.location.lat,
  longitude: gs.location.lon,
  altitude: gs.location.alt,
  status: gs.status || "Active",
  frequency: gs.frequency,
  bandType: gs.bandType || "S",
  elevation: gs.elevation || 5,
  azimuth: gs.azimuth || 360,
  operator: gs.operator,
  established: gs.established ? new Date(gs.established).toISOString().split('T')[0] : undefined,
  description: gs.description,
  lastUpdate: gs.updatedAt ? new Date(gs.updatedAt).toISOString() : new Date().toISOString(),
});

// Fetch ground stations from MongoDB API
export const fetchApiGroundStations = async (): Promise<DisplayGroundStation[]> => {
  try {
    const response = await fetch("/api/ground-stations");
    if (!response.ok) {
      throw new Error(`API request failed: ${response.status}`);
    }
    const groundStations: ApiGroundStation[] = await response.json();
    return groundStations.map(convertApiGroundStationToDisplay);
  } catch (error) {
    console.error("Error fetching API ground stations:", error);
    return [];
  }
};

// Get predefined ground stations
export const getPredefinedGroundStations = (): DisplayGroundStation[] => {
  return PREDEFINED_GROUND_STATIONS;
};

// Get display ground stations by merging API and predefined data
export const getDisplayGroundStations = (apiGroundStations: any[]): DisplayGroundStation[] => {
  // Convert API ground stations to DisplayGroundStation format
  const convertedApiGS: DisplayGroundStation[] = apiGroundStations.map(gs => convertApiGroundStationToDisplay(gs));
  
  // Get predefined ground stations
  const predefinedGS = getPredefinedGroundStations();
  
  // Merge both sources
  return mergeGroundStationSources(convertedApiGS, predefinedGS);
};

// Merge ground stations from different sources, removing duplicates by name and location
export const mergeGroundStationSources = (
  apiGroundStations: DisplayGroundStation[],
  predefinedGroundStations: DisplayGroundStation[]
): DisplayGroundStation[] => {
  const merged = [...apiGroundStations];
  const existingStations = new Set(
    apiGroundStations.map(gs => `${gs.name}-${gs.latitude.toFixed(3)}-${gs.longitude.toFixed(3)}`)
  );
  
  // Add predefined stations that don't already exist in API data
  predefinedGroundStations.forEach(gs => {
    const key = `${gs.name}-${gs.latitude.toFixed(3)}-${gs.longitude.toFixed(3)}`;
    if (!existingStations.has(key)) {
      merged.push(gs);
    }
  });
  
  return merged.sort((a, b) => a.name.localeCompare(b.name));
};

// Get ground station statistics
export const getGroundStationStats = (groundStations: DisplayGroundStation[]) => ({
  total: groundStations.length,
  active: groundStations.filter(gs => gs.status === "Active").length,
  inactive: groundStations.filter(gs => gs.status === "Inactive").length,
  maintenance: groundStations.filter(gs => gs.status === "Maintenance").length,
  decommissioned: groundStations.filter(gs => gs.status === "Decommissioned").length,
  sBand: groundStations.filter(gs => gs.bandType === "S").length,
  xBand: groundStations.filter(gs => gs.bandType === "X").length,
  kaBand: groundStations.filter(gs => gs.bandType === "Ka").length,
  kuBand: groundStations.filter(gs => gs.bandType === "Ku").length,
  lBand: groundStations.filter(gs => gs.bandType === "L").length,
  cBand: groundStations.filter(gs => gs.bandType === "C").length,
  api: groundStations.filter(gs => gs.source === "api").length,
  predefined: groundStations.filter(gs => gs.source === "predefined").length,
  custom: groundStations.filter(gs => gs.source === "custom").length,
  countries: new Set(groundStations.map(gs => gs.country)).size,
});
